modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Ikisugi GNU LGPLv3"

[[mods]]
modId = "yajusenpai"
version = "${version}"
displayName = "Yaju Senpai"
authors = "MORIMORI0317, toranpfan6433"
displayURL = "https://modrinth.com/mod/yaju-senpai"
issueTrackerURL = "https://github.com/MORIMORI0317/YajuSenpaiMOD/issues"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/YajuSenpaiMOD/master/neoforge_version_check.json"
description = '''
The Ikisugi MOD.

使用BB
野樹先輩BB
https://www.nicovideo.jp/watch/sm26250744
りんごＢＢ
https://www.nicovideo.jp/watch/sm18145645
サイクロップス先輩のバイザー・サングラスＢＢ.XMEN
https://www.nicovideo.jp/watch/sm25377226
野獣先輩のでか枕BB
https://www.nicovideo.jp/watch/sm19360333
回るOバック（この世の終わりみたいなパンツ）.NKTIDKSG
https://www.nicovideo.jp/watch/sm33170971
など...

使用音源
淫ク☆ Sounds (リンク切れ)
https://inc-sounds.net/
Kaede Games Mini
https://mini.kaedeee.com/
課長こわれる　ドマラCD
https://www.nicovideo.jp/watch/sm22464402
サイクロップス先輩　ドラマCD　long ver.
https://www.nicovideo.jp/watch/sm26268020
家臣に毒を盛られ討死する武田信玄
https://www.nicovideo.jp/watch/sm35647021
など...

参考MOD
野獣先輩MOD
https://web.archive.org/web/20160713103301/http://forum.minecraftuser.jp/viewtopic.php?f=13&t=1758&p=208860#p208860
野　獣　ブ　ロ　ッ　ク.mod
https://www.nicovideo.jp/watch/sm29641439
など...
'''
logoFile = "logo.png"

[modproperties.yajusenpai]
catalogueImageIcon = "icon.png"

[[dependencies.yajusenpai]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.167,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yajusenpai]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yajusenpai]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "yajusenpai-common.mixins.json"

[[mixins]]
config = "yajusenpai.mixins.json"